// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UpgradedCrawler.Core.Data;

#nullable disable

namespace UpgradedCrawler.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525042710_AddAssignmentAnalysis")]
    partial class AddAssignmentAnalysis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("UpgradedCrawler.Core.Entities.AssignmentAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColdEmailDraft")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverLetterDraft")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId", "ProviderId")
                        .IsUnique()
                        .HasDatabaseName("IX_AssignmentAnalyses_AssignmentId_ProviderId");

                    b.ToTable("AssignmentAnalyses");
                });

            modelBuilder.Entity("UpgradedCrawler.Core.Entities.AssignmentAnnouncement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId", "ProviderId")
                        .IsUnique()
                        .HasDatabaseName("IX_Assignments_AssignmentId_ProviderId");

                    b.ToTable("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
